In [1]:
print("hello world")

hello world


In [2]:
help("keywords")


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 



In [4]:
true=15
print(true)

15


In [ ]:
#python is case sensetive

In [7]:
a=40
print(type(a))
type(a)

<class 'int'>


int

In [26]:
ap="fjejejen fjwfknnfe   cncklllskdo"
print(ap[0::2])
print(ap[::-1])

feee jfnf  nklsd
odkslllkcnc   efnnkfwjf nejejejf


In [29]:
k="python"
op=k.upper()
lo=op.lower()
ol=k.casefold()#converts to lower case
print(op,lo,ol)

PYTHON python python


In [42]:
op="12344"
os="awws"
ok="sword shield nothing"
print(op.isdigit(),os.isalpha(),os.isdigit(),op.isdecimal(),ok.split())

True True False True ['sword', 'shield', 'nothing']


In [73]:
k=[1,2,3,4,5,"df",[1,2,"dl",123]]
k[6].append("loki joki")
k.insert(1,3)
k[7].insert(1,20)
k.extend([15,12,34])
for i in k:
    print(i,end="  ")
k.clear()
print(k)

1  3  2  3  4  5  df  [1, 20, 2, 'dl', 123, 'loki joki']  15  12  34  []


In [81]:
k=[1,2,3,4,5,"df",[1,2,"dl",123]]
op=[1,3,4,2,5,3,1,7,8]
m=k.copy()
print(m)
op.sort()
op
op.sort(reverse=True)
op

[1, 2, 3, 4, 5, 'df', [1, 2, 'dl', 123]]


[8, 7, 5, 4, 3, 3, 2, 1, 1]

In [1]:
t=(1,2,3,4,5,6,7)
type(t)

tuple

In [5]:
s={1,2,3,4,5,6,7,8,9,0}
print(type(s))
sp={1:2,3:4}
print(type(sp))
t={1,1,2,2,3,3,3,3,4,4,4,4,44,5}
print(t)

<class 'set'>
<class 'dict'>
{1, 2, 3, 4, 5, 44}


In [12]:
a={1,2,3,4,5,6}
b={7,8,9,10,11,12,3,4,5}
print(a.union(b))
print(a|b)
print(a.intersection(b))
print(a&b)


{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
{3, 4, 5}
{3, 4, 5}


In [19]:
a={1,2,3,4,5,6,7,8,9,0,10}
b={1,2,3,6,7,}
print(b.issubset(a))
print(a.issuperset(b))
a.add(15)
print(a)
a.remove(0)
print(a)

True
True
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15}


In [37]:
ok={"name":1,"sa":20,"op":"aa"}
print(ok)
print(ok.keys())
print(ok.values())
print(ok.items())
ok.update({"roll_no":23})
print(ok)
ok.clear()
ok

{'name': 1, 'sa': 20, 'op': 'aa'}
dict_keys(['name', 'sa', 'op'])
dict_values([1, 20, 'aa'])
dict_items([('name', 1), ('sa', 20), ('op', 'aa')])
{'name': 1, 'sa': 20, 'op': 'aa', 'roll_no': 23}


{}

In [31]:
a=15
b=4
print(a+b,a-b,a*b,a/b,a%b,a//b,a**b)

19 11 60 3.75 3 3 50625


In [36]:
k=input("enter a character")
ko=int(input("number"))
print(k*ko)

enter a character 12
number 12


121212121212121212121212


In [38]:
if 20>30:
    print("right")
else:
    print("wrong")

wrong


In [49]:
ko=input("Enter y to continue:")
while ko=="y":
    k=input("Enter An Alphabet:")
    op="AEIOU"
    if k.upper() in op:
        print("It is a Vowel")
    else:
        print("It is a Consonant")
    ko=input("Enter y to continue:")

Enter y to continue: y
Enter An Alphabet: a


It is a Vowel


Enter y to continue: y
Enter An Alphabet: e


It is a Vowel


Enter y to continue: y
Enter An Alphabet: b


It is a Consonant


Enter y to continue: n


In [27]:

for i in range(0,101,1):
    print(i,end=",")
print() 
for i in range(100,-1,-1): 
    print(i,end=",")

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,
100,99,98,97,96,95,94,93,92,91,90,89,88,87,86,85,84,83,82,81,80,79,78,77,76,75,74,73,72,71,70,69,68,67,66,65,64,63,62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,

In [14]:
for i in range(0,101,2):
    print(i,end=" ")

0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100 

In [20]:
#wap to print multipilcation table
k=int(input("enter number"))
for i in range(1,11):
    print(k,"x",i,"=",k*i)

enter number 5


5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [28]:
#wap to print no of alphabet,digits,special characters
k=input("word:")
dig=0
alb=0
sc=0
for i in (k):
    if i.isdigit():
        dig+=1
    elif i.isalpha():
        alb+=1
    else:
        sc+=1
print("\nno of digits:",dig,"\nno of alphabet:",alb,"\nno of special character:",sc)
        

word: loki is no 1 gay



no of digits: 1 
no of alphabet: 11 
no of special character: 4


In [31]:
k=input("word:")
vow=0
con=0
op="AEIOU"
for i in k:
    if i.upper() in op:
        vow+=1
    elif i ==" ":
        co=1
    else:
        con+=1
print("no of vowel:",vow,"no of consonant:",con)
    

word: ss aa ww 


no of vowel: 2 no of consonant: 4


In [33]:
i=1
while i<=5:
    print(i)
    i+=1

1
2
3
4
5


In [36]:
k=200
while k>=100:
    if k%5==0:
        print(k,end=" ")
    k=k-1

200 195 190 185 180 175 170 165 160 155 150 145 140 135 130 125 120 115 110 105 100 

In [37]:
k=int(input("enter number"))
op=1
while op<11:
    print(k,"x",op,"=",k*op)
    op+=1

enter number 5


5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [43]:
k=input("rock,paper,scissor")
while True:
    if k.lower() not in["rock","paper","scissor"]:
        k=input(" please rock,paper,scissor")
    else:
        print(k)
        break

rock,paper,scissor sci
 please rock,paper,scissor scissor


scissor


In [42]:
choice=''
while choice.lower() not in ['rock','paper','scissor']:
    choice=input("choice")
print(choice)

choice rock


rock


In [47]:
k=int(input("enter start"))
p=int(input("enter stop"))
l=0
c=0
for i in range(k,p+1):
    l=l+i
    c+=1
op=l/c
print("average of the range:",op)
    

enter start 1
enter stop 90


average of the range: 45.5


In [49]:
k=int(input("enter start"))
p=int(input("enter stop"))
l=0
c=0
while k<=p:
    l+=k
    c+=1
    k+=1
op=l/c
print("average of the range:",op)

enter start 1
enter stop 9


average of the range: 5.0


In [55]:
def greet():
    print("hello")
def add():
    a=int(input("enter a value"))
    b=int(input("enter a value"))
    print("sum--",a+b)
def add1(x,y):
    print("sum----",x+y)
greet()
add()
add1(12,34)

hello


enter a value 12
enter a value 34


sum-- 46
sum---- 46


In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
a=np.array([1,2,3,45,4,5,6])
print(a)
print(type(a))
ap=np.array((1,2,3,4,5,6,7,8,9))
print(ap)

[ 1  2  3 45  4  5  6]
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


In [3]:
a=np.array([1,2,3,4,5,'abc',23.6])
a

array(['1', '2', '3', '4', '5', 'abc', '23.6'], dtype='<U32')

In [4]:
a=np.array({1,2,3,4,5,6,7,8,9})
a

array({1, 2, 3, 4, 5, 6, 7, 8, 9}, dtype=object)

In [5]:
ap=np.array([[1,2,3],[4,5,6]])
ap

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
ap[0,0]

1

In [7]:
#slicing on a 2d array
#var[row_slicing,column_slicing]
#row_slicing[start:stop+1:step]
#column_slicing[start:stop+1:step]
an=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(an)
an[1:3:1,1:3:1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[5, 6],
       [8, 9]])

In [8]:
#check dimension
an.ndim


2

In [9]:
#ndmin():show the maximum number of dimention we can create
a=np.array([5],ndmin=32)
a

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [10]:
#arrange():generate a sequence of integer between any given interval
a=np.arange(1,20,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:
a=np.arange(100,0,-2)
a

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6,   4,   2])

In [12]:
#zeroes():returns a matrix full of zeroes
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
a=np.zeros((2,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
#ones():return a 1D matrix full of one.
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
#full():return a matrix filled with the specified number
np.full((6,7),9)

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [17]:
#random nubers in numpy
#return a random number between 0-1
np.random.rand()

0.9748791575901119

In [18]:
np.random.rand(10)

array([0.26077076, 0.22934518, 0.18918677, 0.09841206, 0.84977171,
       0.52886826, 0.1784685 , 0.50382943, 0.24782528, 0.16486266])

In [19]:
np.random.randint(100)

32

In [20]:
np.random.randint(1,100,(5,5))

array([[38, 48,  3, 96,  7],
       [76, 53, 24, 71, 47],
       [51, 30, 40, 68, 89],
       [46, 48, 28,  1, 85],
       [53, 61, 71, 50, 22]])

In [190]:
o=np.array([1,2,3,4,5,6,7])
b=np.array([10,20,30,40,50,60,70])
print(o)
print(b)



[1 2 3 4 5 6 7]
[10 20 30 40 50 60 70]


In [196]:
print(np.add(o,b))
print(np.subtract(o,b))
print(np.multiply(o,b))
print(np.divide(o,b))
print(np.power(o,9))

[11 22 33 44 55 66 77]
[ -9 -18 -27 -36 -45 -54 -63]
[ 10  40  90 160 250 360 490]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[       1      512    19683   262144  1953125 10077696 40353607]


In [207]:
###statistical operationns
c=np.random.randint(1,60,(2,4))
c
print(c)

[[33 46 44 22]
 [11 32 20 33]]


In [204]:
#min():returns the minimum value present in array
np.min(c)

13

In [205]:
#max():returns the maximum value present in the array
np.max(c)

52

In [208]:
#argmin():returns the index position of lowest value
np.argmin(c)


4

In [210]:
#argmax():returns the index position of max value
np.argmax(c)

1

In [211]:
np.mean(c)


30.125

In [214]:
#concatination of two array
#we can join array in two ways 
#1-column wise
#2-row wise
a=np.random.randint(1,50,(2,2))
b=c
c=np.random.randint(1,50,(4,4))
print(a)
print(b)
print(c)


[[34 20]
 [24  9]]
[[15 25 15 12]
 [18 36 35 46]]
[[45 30 43 11]
 [25 30 43 26]
 [44 29 42 46]
 [23 20 31 14]]


In [220]:
#concatenating the arrays along with the columns
#the row size must be same
#axis=1 represent the columns
print(np.concatenate((a,b),axis=1))

[[34 20 15 25 15 12]
 [24  9 18 36 35 46]]


In [222]:
#concatenating the arrays along with the rows
#the column size must be same
#axis=0 represent the row
print(np.concatenate((b,c),axis=0))

[[15 25 15 12]
 [18 36 35 46]
 [45 30 43 11]
 [25 30 43 26]
 [44 29 42 46]
 [23 20 31 14]]


In [223]:
#stacking of two arrays
#1->hstack--horizontal stack(joining along with column)
#2->vstack--vertical stack(joining along with row)
np.hstack((a,b))

array([[34, 20, 15, 25, 15, 12],
       [24,  9, 18, 36, 35, 46]])

In [225]:
np.vstack((b,c))

array([[15, 25, 15, 12],
       [18, 36, 35, 46],
       [45, 30, 43, 11],
       [25, 30, 43, 26],
       [44, 29, 42, 46],
       [23, 20, 31, 14]])

In [229]:
#reshape():changing the dimentiom of an array  without changing values
a=np.random.randint(1,50,size=10)
print("dimention---->",a.ndim)
print("shape----->",a.shape)
print(a)

dimention----> 1
shape-----> (10,)
[26 44 29 39  6 35 47 22 13 25]


In [233]:
x=a.reshape(2,5)
print(x)
print("dimention---->",x.ndim)
print("shape----->",x.shape)

[[26 44 29 39  6]
 [35 47 22 13 25]]
dimention----> 2
shape-----> (2, 5)


In [239]:
#flatten():convert a n-dimentional array to 1-D array
y=np.random.randint(1,500,(50,50))
print(y)
print("dimention---->",y.ndim)
print("shape----->",y.shape)

[[354 174 222 ... 169 190  12]
 [354 460 424 ... 233  13 198]
 [411 231  15 ... 162 406 379]
 ...
 [310 389 314 ... 333 222  79]
 [205 156 334 ... 181   9 111]
 [  9  72 470 ... 151 371 493]]
dimention----> 2
shape-----> (50, 50)


In [241]:
y1=y.flatten()
print(y1)
print("dimention---->",y1.ndim)
print("shape----->",y1.shape)

[354 174 222 ... 151 371 493]
dimention----> 1
shape-----> (2500,)
